# Generated by Django 5.0.3 on 2024-04-09 18:21

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام آهنگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('release', django_jalali.db.models.jDateField(verbose_name='تاریخ انتشار')),
                ('spotify', models.TextField(blank=True, null=True, verbose_name='لینک اسپاتیفای این آهنگ')),
                ('apple', models.TextField(blank=True, null=True, verbose_name='لینک اپل موزیک این آهنگ')),
                ('music', models.FileField(blank=True, null=True, upload_to='static_media/media/music/', verbose_name='فایل آهنگ')),
                ('pic', models.FileField(blank=True, null=True, upload_to='static_media/media/pic/', verbose_name='فایل کاور')),
                ('video', models.FileField(blank=True, null=True, upload_to='static_media/media/video/', verbose_name='فایل موزیک ویدئو')),
            ],
            options={
                'verbose_name_plural': 'موزیک ها',
            },
        ),
    ]
