# Generated by Django 5.0.3 on 2024-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='youtube',
            field=models.TextField(blank=True, null=True, verbose_name='لینک یوتیوب این آهنگ'),
        ),
    ]
